/**
 * sd-transforms/dart-constants.format.mjs
 * VoltVenture Design System — Custom Style Dictionary v4 Dart Constants Formatter
 *
 * Produces lib/voltventure_tokens.dart with:
 *  - Private constants (underscore prefix) for primitive tokens
 *  - Public constants (no underscore) for semantic tokens
 *  - Dart doc comments (///) on every exported constant
 *  - Types: const Color (Color(0xFFRRGGBB)), const double, const List<BoxShadow>
 *  - Skips: typography composites and font family strings (handled in voltventure_theme.dart)
 */

/**
 * Convert a camelCase SD token name to a Dart identifier.
 * SD's name/camelCase transform produces e.g. "colorGreen500", "space400".
 * For primitives we prepend underscore: "_colorGreen500".
 */
function dartName(token, isPrimitive) {
  const name = token.name; // already camelCase from name/camelCase transform
  return isPrimitive ? `_${name}` : name;
}

/**
 * Determine if a token is primitive (lives in tokens/primitive/).
 * SD's token.filePath contains the source file path with OS separators.
 */
function isPrimitiveToken(token) {
  const fp = (token.filePath || '').replace(/\\/g, '/');
  return fp.includes('/primitive/');
}

/**
 * Determine if a token should be skipped (not emitted as a Dart constant).
 * Skip: typography composites, font family strings, font weight/tracking/lineHeight primitives
 * (all handled directly in voltventure_theme.dart).
 */
function shouldSkip(token) {
  const type = token.$type || token.type;
  // Skip composite typography tokens
  if (type === 'typography') return true;
  // Skip font.* primitive tokens (family, weight, tracking, lineHeight)
  const pathStr = token.path.join('.');
  if (pathStr.startsWith('font.')) return true;
  return false;
}

/**
 * Derive the Dart declaration for a token given its resolved value and type.
 * Returns { dartType, dartValue } or null if unsupported.
 */
function dartDeclaration(token) {
  const type = token.$type || token.type;
  const value = token.value; // already transformed by registered SD transforms

  switch (type) {
    case 'color':
      // value is e.g. "Color(0xFFC6FF2D)" from voltventure/color/flutter transform
      return { dartType: 'Color', dartValue: value };

    case 'dimension':
      // value is e.g. "16.0" from voltventure/dimension/double transform
      return { dartType: 'double', dartValue: value };

    case 'shadow': {
      // elevation.flat has $value: 'none' → empty list
      if (value === 'none' || value === '' || (Array.isArray(value) && value.length === 0)) {
        return { dartType: 'List<BoxShadow>', dartValue: 'const []' };
      }
      // value is "BoxShadow(...)" string from voltventure/shadow/boxShadow transform
      // Wrap in list syntax
      const listVal = `[${value}]`;
      return { dartType: 'List<BoxShadow>', dartValue: listVal };
    }

    default:
      // Numbers without a type (grid columns, icon sizes that have no $type)
      if (typeof value === 'number') {
        if (Number.isInteger(value)) {
          return { dartType: 'int', dartValue: String(value) };
        }
        return { dartType: 'double', dartValue: `${value}.0` };
      }
      return null; // Skip unsupported types
  }
}

export const dartConstantsFormat = {
  name: 'voltventure/dart/constants',

  /**
   * @param {object} opts
   * @param {import('style-dictionary').Dictionary} opts.dictionary
   */
  format: ({ dictionary }) => {
    const lines = [];

    // -------------------------------------------------------------------------
    // File header
    // -------------------------------------------------------------------------
    lines.push('// AUTO-GENERATED — DO NOT EDIT. Run \'npm run build:tokens\' to regenerate.');
    lines.push('// Generated by Style Dictionary v4 + VoltVenture custom Dart transforms.');
    lines.push('// ignore_for_file: lines_longer_than_80_chars');
    lines.push('');
    lines.push("import 'package:flutter/material.dart';");
    lines.push('');

    // -------------------------------------------------------------------------
    // Separate tokens into primitives and semantics, skip unsupported
    // -------------------------------------------------------------------------
    const primitives = [];
    const semantics = [];

    for (const token of dictionary.allTokens) {
      if (shouldSkip(token)) continue;
      const decl = dartDeclaration(token);
      if (!decl) continue;

      const entry = { token, decl, isPrimitive: isPrimitiveToken(token) };
      if (entry.isPrimitive) {
        primitives.push(entry);
      } else {
        semantics.push(entry);
      }
    }

    // -------------------------------------------------------------------------
    // Emit primitive constants (private — underscore prefix)
    // -------------------------------------------------------------------------
    if (primitives.length > 0) {
      lines.push('// ═══════════════════════════════════════════════════════════');
      lines.push('// Primitive tokens — private (do not reference outside this file)');
      lines.push('// ═══════════════════════════════════════════════════════════');
      lines.push('');

      // Group by type for readability
      const byType = {};
      for (const entry of primitives) {
        const t = entry.decl.dartType;
        if (!byType[t]) byType[t] = [];
        byType[t].push(entry);
      }

      for (const [dartType, entries] of Object.entries(byType)) {
        lines.push(`// — Primitive: ${dartType} —`);
        for (const { token, decl } of entries) {
          const name = `_${token.name}`;
          const description = token.$description || token.description || '';
          if (description) {
            lines.push(`/// ${token.path.join('.')}${description ? ` — ${description}` : ''}`);
          }
          lines.push(`const ${dartType} ${name} = ${decl.dartValue};`);
        }
        lines.push('');
      }
    }

    // -------------------------------------------------------------------------
    // Emit semantic constants (public — no underscore)
    // -------------------------------------------------------------------------
    if (semantics.length > 0) {
      lines.push('// ═══════════════════════════════════════════════════════════');
      lines.push('// Semantic tokens — public API');
      lines.push('// ═══════════════════════════════════════════════════════════');
      lines.push('');

      const byType = {};
      for (const entry of semantics) {
        const t = entry.decl.dartType;
        if (!byType[t]) byType[t] = [];
        byType[t].push(entry);
      }

      for (const [dartType, entries] of Object.entries(byType)) {
        lines.push(`// — Semantic: ${dartType} —`);
        for (const { token, decl } of entries) {
          const name = token.name;
          const description = token.$description || token.description || '';
          lines.push(`/// ${token.path.join('.')}${description ? ` — ${description}` : ''}`);
          lines.push(`const ${dartType} ${name} = ${decl.dartValue};`);
        }
        lines.push('');
      }
    }

    return lines.join('\n');
  },
};
