/**
 * sd-transforms/ts-constants.format.mjs
 * VoltVenture Design System — Custom Style Dictionary v4 TypeScript Constants Formatter
 *
 * Produces lib/voltventure_tokens.ts with:
 *  - Private constants (no export) for primitive tokens
 *  - Public exported constants for semantic tokens
 *  - Types: hex string for colors, number for dimensions
 *  - Skips: typography composites, font family strings, shadow tokens
 */

/**
 * Determine if a token is primitive (lives in tokens/primitive/).
 */
function isPrimitiveToken(token) {
  const fp = (token.filePath || '').replace(/\\/g, '/');
  return fp.includes('/primitive/');
}

/**
 * Determine if a token should be skipped (not emitted as a TS constant).
 * Skip: typography composites, font.* tokens, shadow tokens
 */
function shouldSkip(token) {
  const type = token.$type || token.type;
  if (type === 'typography') return true;
  if (type === 'shadow') return true;
  const pathStr = token.path.join('.');
  if (pathStr.startsWith('font.')) return true;
  return false;
}

/**
 * Produce the TypeScript value literal for a token.
 * Returns null if the token type is unsupported.
 */
function tsValueLiteral(token) {
  const type = token.$type || token.type;
  const value = token.$value; // SD v4 DTCG: transformed value stored in $value

  switch (type) {
    case 'color':
      // After color/hex transform, value is '#RRGGBB' hex string
      return `'${value}'`;

    case 'dimension':
      // DTCG $value is already a number (e.g., 16)
      return String(parseFloat(String(value)));

    default:
      // Untyped numbers (e.g., grid.columns = 4)
      if (typeof value === 'number') {
        return String(value);
      }
      return null;
  }
}

export const tsConstantsFormat = {
  name: 'voltventure/ts/constants',

  /**
   * @param {object} opts
   * @param {import('style-dictionary').Dictionary} opts.dictionary
   */
  format: ({ dictionary }) => {
    const lines = [];

    // -------------------------------------------------------------------------
    // File header
    // -------------------------------------------------------------------------
    lines.push("// AUTO-GENERATED — DO NOT EDIT. Run 'npm run build:tokens' to regenerate.");
    lines.push('// Generated by Style Dictionary v4 + VoltVenture custom TS transforms.');
    lines.push('');

    // -------------------------------------------------------------------------
    // Separate tokens into primitives and semantics, skip unsupported
    // -------------------------------------------------------------------------
    const primitives = [];
    const semantics = [];

    for (const token of dictionary.allTokens) {
      if (shouldSkip(token)) continue;
      const literal = tsValueLiteral(token);
      if (literal === null) continue;

      const entry = { token, literal, isPrimitive: isPrimitiveToken(token) };
      if (entry.isPrimitive) {
        primitives.push(entry);
      } else {
        semantics.push(entry);
      }
    }

    // -------------------------------------------------------------------------
    // Emit primitive constants (not exported)
    // -------------------------------------------------------------------------
    if (primitives.length > 0) {
      lines.push('// ═══════════════════════════════════════════════════════════');
      lines.push('// Primitive tokens — not exported (internal use only)');
      lines.push('// ═══════════════════════════════════════════════════════════');
      lines.push('');

      for (const { token, literal } of primitives) {
        const description = token.$description || token.description || '';
        if (description) {
          lines.push(`/** ${token.path.join('.')} — ${description} */`);
        }
        lines.push(`const ${token.name} = ${literal};`);
      }
      lines.push('');
    }

    // -------------------------------------------------------------------------
    // Emit semantic constants (exported public API)
    // -------------------------------------------------------------------------
    if (semantics.length > 0) {
      lines.push('// ═══════════════════════════════════════════════════════════');
      lines.push('// Semantic tokens — public API');
      lines.push('// ═══════════════════════════════════════════════════════════');
      lines.push('');

      for (const { token, literal } of semantics) {
        const description = token.$description || token.description || '';
        if (description) {
          lines.push(`/** ${token.path.join('.')} — ${description} */`);
        }
        lines.push(`export const ${token.name} = ${literal};`);
      }
      lines.push('');
    }

    return lines.join('\n');
  },
};
