// AUTO-GENERATED — DO NOT EDIT. Run 'npm run build:tokens' to regenerate.
// Generated by Style Dictionary v4 + VoltVenture custom RN Paper theme formatter.

import { MD3LightTheme } from 'react-native-paper';
import type { MD3Theme } from 'react-native-paper';
import * as tokens from './voltventure_tokens';

/** Creates the VoltVenture React Native Paper MD3 theme. */
/** Uses the spread strategy — MD3LightTheme fills all required color roles; */
/** only roles with explicit VoltVenture semantic tokens are overridden. */
export function createVoltVentureTheme(): MD3Theme {
  return {
    ...MD3LightTheme,
    colors: {
      ...MD3LightTheme.colors,
      /** Electric Green — primary CTA background */
      primary: tokens.colorActionPrimary,
      /** Volt Black — secondary CTA background */
      secondary: tokens.colorActionSecondary,
      /** White — primary light surface */
      background: tokens.colorSurfaceBase,
      /** White — default card/sheet surface */
      surface: tokens.colorSurfaceBase,
      /** Volt Black — text and icons on light surfaces */
      onSurface: tokens.colorTextPrimary,
      /** Light grey — dividers and non-interactive borders */
      outline: tokens.colorBorderSubtle,
    },
  };
}
