// AUTO-GENERATED — DO NOT EDIT. Run 'npm run build:tokens' to regenerate.
// Generated by Style Dictionary v4 + VoltVenture custom TS transforms.

// ═══════════════════════════════════════════════════════════
// Primitive tokens — not exported (internal use only)
// ═══════════════════════════════════════════════════════════

/** border.width.none — Default for filled surfaces — no visible border */
const borderWidthNone = 0;
/** border.width.hairline — Dividers, outlined chips, input rest state. Paired with color.border.subtle. */
const borderWidthHairline = 1;
/** border.width.strong — Input focus, selected card. Paired with color.border.strong. */
const borderWidthStrong = 1.5;
/** border.width.focus — Keyboard / switch-control focus ring, 2pt offset. Always green (color.action.primary). Visible on both light and dark surfaces. */
const borderWidthFocus = 2;
/** color.black — Volt Black — canvas color and primary foreground. All text, icons, and UI on light surfaces. */
const colorBlack = '#0f0f0f';
/** color.white — Pure White — primary light surface. Base background for all light-mode screens. */
const colorWhite = '#ffffff';
/** color.grey.100 — List row fill, settings surface */
const colorGrey100 = '#f5f5f5';
/** color.grey.200 — Inactive nav circle, dividers on light surfaces */
const colorGrey200 = '#ebebeb';
/** color.grey.300 — Interpolated — disabled text and decorative elements */
const colorGrey300 = '#c9c9c9';
/** color.grey.500 — Brand board Mid Gray — secondary text. 3.9:1 on white; passes AA for large text only. */
const colorGrey500 = '#808080';
/** color.grey.700 — Interpolated — dark-surface borders and secondary elements */
const colorGrey700 = '#4a4a4a';
/** color.grey.800 — Brand board Charcoal — progress tracks, elevated dark surfaces */
const colorGrey800 = '#2f2f2f';
/** color.grey.900 — Interpolated — raised dark surface (elevation model B) */
const colorGrey900 = '#1a1a1a';
/** color.grey.950 — Brand board Volt Black alias in grey ramp */
const colorGrey950 = '#0f0f0f';
/** color.grey.050 — List row fill, resting state */
const colorGrey050 = '#fafafa';
/** color.green.100 — Tint background — subtle success wash, hover state fill on light surfaces */
const colorGreen100 = '#f4ffd9';
/** color.green.300 — Hover / focus wash on interactive elements */
const colorGreen300 = '#ddff7a';
/** color.green.500 — Electric Green — primary brand accent. Background only on light surfaces. Foreground must always be color.black. Against white: 1.36:1 (unusable as text). Against black: 15.4:1 (AAA). */
const colorGreen500 = '#c6ff2d';
/** color.green.600 — Pressed state on primary action elements */
const colorGreen600 = '#a8de1a';
/** color.green.700 — Dark green — the only accessible green for text on white surfaces (4.6:1, passes WCAG AA) */
const colorGreen700 = '#7d9220';
/** grid.columns — 4-column phone grid. On larger phones margin is fixed and columns are fluid. */
const gridColumns = 4;
/** grid.margin — Fixed horizontal margin — stays 16pt at all phone sizes. Measured from profile screen: 361pt content in 393pt frame. */
const gridMargin = 16;
/** grid.gutter — Column gutter — 16pt between columns */
const gridGutter = 16;
/** grid.contentWidth — Content width at 393pt reference device (393 - 2 × 16pt margin = 361pt). Reference: iPhone 15/16 logical size. */
const gridContentWidth = 361;
/** grid.touchTarget — Minimum interactive touch target — 48pt above the 44pt iOS / 48dp Android floor. Set higher for in-vehicle one-handed use. */
const gridTouchTarget = 48;
/** icon.canvas — 24pt icon canvas — bounding box for all icons. Icons render at 1× vector. */
const iconCanvas = 24;
/** icon.liveArea — 20pt live area (2pt padding all sides within 24pt canvas). Glyph artwork must fit within this area. */
const iconLiveArea = 20;
/** icon.padding — 2pt padding all sides between canvas edge and live area */
const iconPadding = 2;
/** icon.size.xs — 16pt icon size — small inline icons, metadata */
const iconSizeXs = 16;
/** icon.size.sm — 20pt icon size — secondary navigation, list row icons */
const iconSizeSm = 20;
/** icon.size.md — 24pt icon size — default (matches canvas). Tab bar, buttons, standard UI icons. */
const iconSizeMd = 24;
/** icon.size.lg — 32pt icon size — feature callouts, empty states, large icon moments */
const iconSizeLg = 32;
/** radius.xs — Badges, small chips, progress tracks */
const radiusXs = 8;
/** radius.sm — Inline tags, thumbnails, inputs */
const radiusSm = 12;
/** radius.md — List rows, secondary cards */
const radiusMd = 16;
/** radius.lg — Standard content card */
const radiusLg = 20;
/** radius.xl — Feature cards, the black stat block, map container */
const radiusXl = 28;
/** radius.2xl — Bottom sheets, full-width hero surfaces */
const radius2xl = 36;
/** radius.full — Buttons, pills, avatars, tab bar circles, status dots — fully rounded */
const radiusFull = 999;
/** radius.icon — App icon only — iOS squircle continuous corner mask (22.37% proportional). Do not use as absolute dp; multiply by container size (e.g. 1024 * 0.2237 = 229pt for 1024pt canvas). */
const radiusIcon = 22.37;
/** space.100 — 4pt — label-to-value stacked, fine-grain adjustments */
const space100 = 4;
/** space.200 — 8pt — icon to label gap */
const space200 = 8;
/** space.300 — 12pt — gap between sibling cards */
const space300 = 12;
/** space.400 — 16pt — screen horizontal margin, list row vertical padding */
const space400 = 16;
/** space.500 — 20pt — card internal padding, above tab bar clearance */
const space500 = 20;
/** space.600 — 24pt — button horizontal padding */
const space600 = 24;
/** space.800 — 32pt — gap between sections */
const space800 = 32;
/** space.1000 — 40pt — large section spacing */
const space1000 = 40;
/** space.1200 — 48pt — minimum touch target dimension (above 44pt iOS / 48dp Android floor) */
const space1200 = 48;
/** space.1600 — 64pt — minimum list row height (two-line rows grow from here) */
const space1600 = 64;
/** space.050 — 2pt — minimum spacing unit. Used for icon-to-icon gaps and tight inline spacing. */
const space050 = 2;

// ═══════════════════════════════════════════════════════════
// Semantic tokens — public API
// ═══════════════════════════════════════════════════════════

/** color.surface.base — Primary light surface. Default background for all light-mode screens. */
export const colorSurfaceBase = '#ffffff';
/** color.surface.sunken — Recessed surface. Used for input fields, code blocks, and content wells that sit below the base. */
export const colorSurfaceSunken = '#f5f5f5';
/** color.surface.raised — Elevated card surface. Semantically distinct from base — conveys elevation even when the hex value matches. */
export const colorSurfaceRaised = '#ffffff';
/** color.surface.inverse — Dark surface. Used for tooltips, toasts, and elements that need to contrast sharply against light surfaces. */
export const colorSurfaceInverse = '#0f0f0f';
/** color.text.primary — Primary text. Headlines, body copy, row labels. 19.6:1 on white — AAA. */
export const colorTextPrimary = '#0f0f0f';
/** color.text.secondary — Secondary / supporting text. Subtitles, metadata, captions. 3.9:1 on white — passes AA for large text only. */
export const colorTextSecondary = '#808080';
/** color.text.disabled — Disabled-state text. Non-interactive labels and placeholders. Below AA threshold by design. */
export const colorTextDisabled = '#c9c9c9';
/** color.text.accent — Accent text. Links, highlights, active tab labels. MUST use green.700 (#7D9220) not green.500 (#C6FF2D) — green.700 achieves 4.6:1 on white (WCAG AA). green.500 achieves only 1.36:1 (fails). */
export const colorTextAccent = '#7d9220';
/** color.text.onInverse — Text on inverse (dark) surfaces. Tooltips, toasts, dark cards. */
export const colorTextOnInverse = '#ffffff';
/** color.action.primary — Primary CTA background. Electric Green (#C6FF2D). Background-only on light surfaces — never use as text color. Always pair with action.primary.fg. */
export const colorActionPrimary = '#c6ff2d';
/** color.action.secondary — Secondary CTA background. Volt Black. Used for non-primary actions that need high contrast. */
export const colorActionSecondary = '#0f0f0f';
/** color.border.subtle — Subtle dividers and non-interactive borders. Row separators, section edges. */
export const colorBorderSubtle = '#ebebeb';
/** color.border.strong — Prominent borders. Selected states, focused inputs with dark outline, card stroke on light backgrounds. */
export const colorBorderStrong = '#0f0f0f';
/** color.border.focus — Focus ring color. Electric Green outline on focused interactive elements. Used as a stroke, not a fill. */
export const colorBorderFocus = '#c6ff2d';
/** color.status.live — Live-status indicator. Electric Green dot or badge. Always paired with a text label — never used as sole state indicator. */
export const colorStatusLive = '#c6ff2d';
