// AUTO-GENERATED — DO NOT EDIT. Run 'npm run build:tokens' to regenerate.
// Generated by Style Dictionary v4 + VoltVenture custom Dart transforms.
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/material.dart';

// ═══════════════════════════════════════════════════════════
// Primitive tokens — private (do not reference outside this file)
// ═══════════════════════════════════════════════════════════

// — Primitive: double —
/// border.width.none — Default for filled surfaces — no visible border
const double _borderWidthNone = 0.0;
/// border.width.hairline — Dividers, outlined chips, input rest state. Paired with color.border.subtle.
const double _borderWidthHairline = 1.0;
/// border.width.strong — Input focus, selected card. Paired with color.border.strong.
const double _borderWidthStrong = 1.5;
/// border.width.focus — Keyboard / switch-control focus ring, 2pt offset. Always green (color.action.primary). Visible on both light and dark surfaces.
const double _borderWidthFocus = 2.0;
/// grid.margin — Fixed horizontal margin — stays 16pt at all phone sizes. Measured from profile screen: 361pt content in 393pt frame.
const double _gridMargin = 16.0;
/// grid.gutter — Column gutter — 16pt between columns
const double _gridGutter = 16.0;
/// grid.contentWidth — Content width at 393pt reference device (393 - 2 × 16pt margin = 361pt). Reference: iPhone 15/16 logical size.
const double _gridContentWidth = 361.0;
/// grid.touchTarget — Minimum interactive touch target — 48pt above the 44pt iOS / 48dp Android floor. Set higher for in-vehicle one-handed use.
const double _gridTouchTarget = 48.0;
/// icon.canvas — 24pt icon canvas — bounding box for all icons. Icons render at 1× vector.
const double _iconCanvas = 24.0;
/// icon.liveArea — 20pt live area (2pt padding all sides within 24pt canvas). Glyph artwork must fit within this area.
const double _iconLiveArea = 20.0;
/// icon.padding — 2pt padding all sides between canvas edge and live area
const double _iconPadding = 2.0;
/// icon.size.xs — 16pt icon size — small inline icons, metadata
const double _iconSizeXs = 16.0;
/// icon.size.sm — 20pt icon size — secondary navigation, list row icons
const double _iconSizeSm = 20.0;
/// icon.size.md — 24pt icon size — default (matches canvas). Tab bar, buttons, standard UI icons.
const double _iconSizeMd = 24.0;
/// icon.size.lg — 32pt icon size — feature callouts, empty states, large icon moments
const double _iconSizeLg = 32.0;
/// radius.xs — Badges, small chips, progress tracks
const double _radiusXs = 8.0;
/// radius.sm — Inline tags, thumbnails, inputs
const double _radiusSm = 12.0;
/// radius.md — List rows, secondary cards
const double _radiusMd = 16.0;
/// radius.lg — Standard content card
const double _radiusLg = 20.0;
/// radius.xl — Feature cards, the black stat block, map container
const double _radiusXl = 28.0;
/// radius.2xl — Bottom sheets, full-width hero surfaces
const double _radius2xl = 36.0;
/// radius.full — Buttons, pills, avatars, tab bar circles, status dots — fully rounded
const double _radiusFull = 999.0;
/// radius.icon — App icon only — iOS squircle continuous corner mask (22.37% proportional). Do not use as absolute dp; multiply by container size (e.g. 1024 * 0.2237 = 229pt for 1024pt canvas).
const double _radiusIcon = 22.4;
/// space.100 — 4pt — label-to-value stacked, fine-grain adjustments
const double _space100 = 4.0;
/// space.200 — 8pt — icon to label gap
const double _space200 = 8.0;
/// space.300 — 12pt — gap between sibling cards
const double _space300 = 12.0;
/// space.400 — 16pt — screen horizontal margin, list row vertical padding
const double _space400 = 16.0;
/// space.500 — 20pt — card internal padding, above tab bar clearance
const double _space500 = 20.0;
/// space.600 — 24pt — button horizontal padding
const double _space600 = 24.0;
/// space.800 — 32pt — gap between sections
const double _space800 = 32.0;
/// space.1000 — 40pt — large section spacing
const double _space1000 = 40.0;
/// space.1200 — 48pt — minimum touch target dimension (above 44pt iOS / 48dp Android floor)
const double _space1200 = 48.0;
/// space.1600 — 64pt — minimum list row height (two-line rows grow from here)
const double _space1600 = 64.0;
/// space.050 — 2pt — minimum spacing unit. Used for icon-to-icon gaps and tight inline spacing.
const double _space050 = 2.0;

// — Primitive: Color —
/// color.black — Volt Black — canvas color and primary foreground. All text, icons, and UI on light surfaces.
const Color _colorBlack = Color(0xFF0F0F0F);
/// color.white — Pure White — primary light surface. Base background for all light-mode screens.
const Color _colorWhite = Color(0xFFFFFFFF);
/// color.grey.100 — List row fill, settings surface
const Color _colorGrey100 = Color(0xFFF5F5F5);
/// color.grey.200 — Inactive nav circle, dividers on light surfaces
const Color _colorGrey200 = Color(0xFFEBEBEB);
/// color.grey.300 — Interpolated — disabled text and decorative elements
const Color _colorGrey300 = Color(0xFFC9C9C9);
/// color.grey.500 — Brand board Mid Gray — secondary text. 3.9:1 on white; passes AA for large text only.
const Color _colorGrey500 = Color(0xFF808080);
/// color.grey.700 — Interpolated — dark-surface borders and secondary elements
const Color _colorGrey700 = Color(0xFF4A4A4A);
/// color.grey.800 — Brand board Charcoal — progress tracks, elevated dark surfaces
const Color _colorGrey800 = Color(0xFF2F2F2F);
/// color.grey.900 — Interpolated — raised dark surface (elevation model B)
const Color _colorGrey900 = Color(0xFF1A1A1A);
/// color.grey.950 — Brand board Volt Black alias in grey ramp
const Color _colorGrey950 = Color(0xFF0F0F0F);
/// color.grey.050 — List row fill, resting state
const Color _colorGrey050 = Color(0xFFFAFAFA);
/// color.green.100 — Tint background — subtle success wash, hover state fill on light surfaces
const Color _colorGreen100 = Color(0xFFF4FFD9);
/// color.green.300 — Hover / focus wash on interactive elements
const Color _colorGreen300 = Color(0xFFDDFF7A);
/// color.green.500 — Electric Green — primary brand accent. Background only on light surfaces. Foreground must always be color.black. Against white: 1.36:1 (unusable as text). Against black: 15.4:1 (AAA).
const Color _colorGreen500 = Color(0xFFC6FF2D);
/// color.green.600 — Pressed state on primary action elements
const Color _colorGreen600 = Color(0xFFA8DE1A);
/// color.green.700 — Dark green — the only accessible green for text on white surfaces (4.6:1, passes WCAG AA)
const Color _colorGreen700 = Color(0xFF7D9220);

// — Primitive: List<BoxShadow> —
/// elevation.flat — No shadow — list rows, inline chips, anything inside a card. On dark surfaces use surface lightness steps instead.
const List<BoxShadow> _elevationFlat = [];
/// elevation.raised — Cards resting on screen — rgba(15,15,15,.06) shadow. Hex alpha: 0.06 × 255 = 15.3 ≈ 0F.
const List<BoxShadow> _elevationRaised = [BoxShadow(color: Color(0x0F0F0F0F), offset: Offset(0.0, 2.0), blurRadius: 8.0, spreadRadius: 0.0)];
/// elevation.floating — Tab bar, FAB, sticky CTA — rgba(15,15,15,.10) shadow. Hex alpha: 0.10 × 255 = 25.5 ≈ 1A.
const List<BoxShadow> _elevationFloating = [BoxShadow(color: Color(0x0F0F0F1A), offset: Offset(0.0, 8.0), blurRadius: 24.0, spreadRadius: 0.0)];
/// elevation.overlay — Sheets, modals, dropped panels — rgba(15,15,15,.16) shadow. Hex alpha: 0.16 × 255 = 40.8 ≈ 29.
const List<BoxShadow> _elevationOverlay = [BoxShadow(color: Color(0x0F0F0F29), offset: Offset(0.0, 16.0), blurRadius: 48.0, spreadRadius: 0.0)];

// — Primitive: int —
/// grid.columns — 4-column phone grid. On larger phones margin is fixed and columns are fluid.
const int _gridColumns = 4;

// ═══════════════════════════════════════════════════════════
// Semantic tokens — public API
// ═══════════════════════════════════════════════════════════

// — Semantic: Color —
/// color.surface.base — Primary light surface. Default background for all light-mode screens.
const Color colorSurfaceBase = Color(0xFFFFFFFF);
/// color.surface.sunken — Recessed surface. Used for input fields, code blocks, and content wells that sit below the base.
const Color colorSurfaceSunken = Color(0xFFF5F5F5);
/// color.surface.raised — Elevated card surface. Semantically distinct from base — conveys elevation even when the hex value matches.
const Color colorSurfaceRaised = Color(0xFFFFFFFF);
/// color.surface.inverse — Dark surface. Used for tooltips, toasts, and elements that need to contrast sharply against light surfaces.
const Color colorSurfaceInverse = Color(0xFF0F0F0F);
/// color.text.primary — Primary text. Headlines, body copy, row labels. 19.6:1 on white — AAA.
const Color colorTextPrimary = Color(0xFF0F0F0F);
/// color.text.secondary — Secondary / supporting text. Subtitles, metadata, captions. 3.9:1 on white — passes AA for large text only.
const Color colorTextSecondary = Color(0xFF808080);
/// color.text.disabled — Disabled-state text. Non-interactive labels and placeholders. Below AA threshold by design.
const Color colorTextDisabled = Color(0xFFC9C9C9);
/// color.text.accent — Accent text. Links, highlights, active tab labels. MUST use green.700 (#7D9220) not green.500 (#C6FF2D) — green.700 achieves 4.6:1 on white (WCAG AA). green.500 achieves only 1.36:1 (fails).
const Color colorTextAccent = Color(0xFF7D9220);
/// color.text.onInverse — Text on inverse (dark) surfaces. Tooltips, toasts, dark cards.
const Color colorTextOnInverse = Color(0xFFFFFFFF);
/// color.action.primary — Primary CTA background. Electric Green (#C6FF2D). Background-only on light surfaces — never use as text color. Always pair with action.primary.fg.
const Color colorActionPrimary = Color(0xFFC6FF2D);
/// color.action.secondary — Secondary CTA background. Volt Black. Used for non-primary actions that need high contrast.
const Color colorActionSecondary = Color(0xFF0F0F0F);
/// color.border.subtle — Subtle dividers and non-interactive borders. Row separators, section edges.
const Color colorBorderSubtle = Color(0xFFEBEBEB);
/// color.border.strong — Prominent borders. Selected states, focused inputs with dark outline, card stroke on light backgrounds.
const Color colorBorderStrong = Color(0xFF0F0F0F);
/// color.border.focus — Focus ring color. Electric Green outline on focused interactive elements. Used as a stroke, not a fill.
const Color colorBorderFocus = Color(0xFFC6FF2D);
/// color.status.live — Live-status indicator. Electric Green dot or badge. Always paired with a text label — never used as sole state indicator.
const Color colorStatusLive = Color(0xFFC6FF2D);
